### ISSUE TITLE
BinaryBuilder Perple_X dependency?

### ISSUE THREAD

**Issue by boriskaus** [brenhinkeller/StatGeochem.jl#28]
I just came across this, and it seems super-useful (particularly the Perple_X interface). 

Yet, from my experience with using codes in teaching, many (geoscience) students will have issues with installing the required software on their respective machines (e.g., Perple_X). 
Have you considered creating a [BinaryBuilder version](https://binarybuilder.org) of Perple_X? 
In the ideal case, this will create precompiled binary versions of Perple_X that run on most currently used operating systems. You would only have to include Perple_X_jll as a dependency.

**Comment by brenhinkeller** [comment]
I'd love to have a Perple_X_jll! I've never actually made a JLL package yet, but maybe it's time. One catch might be licensing -- we'll probably have to reach out to Connolly

**Comment by boriskaus** [comment]
yes good point; the current version of Perple_X does indeed not allow that (even when it is already distributed as open source code). Email to Jamie is on the way.

**Comment by boriskaus** [comment]
`Perple_X_jll` is now [available](https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl) and appears to work on all available systems. 
It is build using this [binary builder script](https://github.com/JuliaPackaging/Yggdrasil/blob/master/P/Perple_X/build_tarballs.jl) from the [github repository](https://github.com/jadconnolly/Perple_X) that Jamie created to store the latest versions of the code

It would be fantastic to update `StatGeochem.jl` to use the `*.jll` version by default (you can always have an option to override this & use a local version). 
Alternatively, one can think about creating a separate `Perple_X.jl` repository that only contains the interface to `Perple_X` (and make that a dependency of `StatGeochem.jl`.

Note that `Perple_X_jll` has the binaries of all files, as well as dynamic libraries of them. If someone has energy, they could write Julia wrappers to these dynamic libraries and directly use (parts of) Perple_X from Julia, w/out having to write files to disk.

**Comment by brenhinkeller** [comment]
Awesome, nice work on the jll! I’ll put it on the agenda — should be fairly easy to switch as long as the perplex interface hasn't changed too much from the perplex v6.8.7 I’ve been working with

**Comment by brenhinkeller** [comment]
Closed by #68 !
